### 2.1 내 정보 조회
// @no-log
GET {{host_url}}/api/v1/users/details

### 2.2 유저 정보 조회
// @no-log
GET {{host_url}}/api/v1/users/2/details

### 2.3 유저 정보 수정
// @no-log
PUT {{host_url}}/api/v1/users
Content-Type: application/json

{
  "img_url": "https://giggle-inglo.s3.ap-northeast-2.amazonaws.com/companies/account_bcbcbc/company_img/04873c73-aff8-4e4f-811b-2251e6c0d75d",
  "introduction": "안녕하세요. 저는 개발자입니다.",
  "stacks": [
    "java",
    "spring"
  ],
  "links": [
    {
      "type": "GITHUB",
      "url": "https://github.com/dongkyeomjang"
    },
    {
      "type": "NOTION",
      "url": "https://shared-havarti-bc1.notion.site/?pvs=74"
    },
    {
      "type": "BLOG",
      "url": "https://velog.io/@sangpok/Github-%ED%98%91%EC%97%85-%EC%84%A4%EC%A0%95Github-Issue-Jira-%EC%97%B0%EB%8F%99"
    },
    {
      "type": "LINKEDIN",
      "url": "https://www.linkedin.com/in/dongkyeomjang0404/"
    },
    {
      "type": "ETC",
      "url": "www.dev.giggle-inglo.com"
    }
  ]
}