### 2.1 내 정보 조회
// @no-log
GET {{host_url}}/api/v1/users/details

### 2.2 유저 정보 조회
// @no-log
GET {{host_url}}/api/v1/users/2/details

### 2.3 어드민 유저 간단 리스트 조회
// @no-log
GET {{host_url}}/api/v1/admins/users/briefs?generation=4&univ-id=1

### 2.4 어드민 유저 요약 리스트 조회
// @no-log
GET {{host_url}}/api/v1/admins/users/overviews?page=1&size=10&generation=4&univ-id=1&search=은

### 2.5 어드민 유저 상세 조회
// @no-log
GET {{host_url}}/api/v1/admins/users/4/details?generation=4

### 2.6 유저 정보 수정
// @no-log
PUT {{host_url}}/api/v1/users
Content-Type: application/json

{
  "img_url": "https://giggle-inglo.s3.ap-northeast-2.amazonaws.com/companies/account_bcbcbc/company_img/04873c73-aff8-4e4f-811b-2251e6c0d75d",
  "introduction": "안녕하세요. 저는 개발자입니다.",
  "stacks": [
    "java",
    "spring"
  ],
  "links": [
    {
      "type": "GITHUB",
      "url": "https://github.com/dongkyeomjang"
    },
    {
      "type": "NOTION",
      "url": "https://shared-havarti-bc1.notion.site/?pvs=74"
    },
    {
      "type": "BLOG",
      "url": "https://velog.io/@sangpok/Github-%ED%98%91%EC%97%85-%EC%84%A4%EC%A0%95Github-Issue-Jira-%EC%97%B0%EB%8F%99"
    },
    {
      "type": "LINKEDIN",
      "url": "https://www.linkedin.com/in/dongkyeomjang0404/"
    },
    {
      "type": "ETC",
      "url": "www.dev.giggle-inglo.com"
    }
  ]
}

### 2.7 어드민 유저 수정
// @no-log
PUT {{host_url}}/api/v1/admins/users/4
Content-Type: application/json

{
  "name": "장동겸",
  "univ_id": 1,
  "email": "jangelliot0404@dgu.ac.kr",
  "phone_number": "01056175155",
  "generation": [2,3,4]
}

### 2.8 어드민 유저 삭제
// @no-log
DELETE {{host_url}}/api/v1/admins/users/5

### 6.1 어드민 유니브 생성
// @no-log
POST {{host_url}}/api/v1/admins/univs
Content-Type: application/json

{
  "name": "테스트 유니브",
  "instagram_url": "https://www.instagram.com/dongguk/",
  "generation": 4
}

### 6.2 어드민 유니브 간단 리스트 조회
// @no-log
GET {{host_url}}/api/v1/admins/univs/briefs?generation=4

### 6.3 어드민 유니브 상세 조회
// @no-log
GET {{host_url}}/api/v1/admins/univs/1/details

### 6.4 어드민 유니브 수정
// @no-log
PUT {{host_url}}/api/v1/admins/univs/1
Content-Type: application/json

{
  "name": "구름대학교",
  "instagram_url": "https://www.instagram.com/goorm/",
  "leader_id": 2
}

### 6.5 어드민 유니브 삭제
// @no-log
DELETE {{host_url}}/api/v1/admins/univs/4