### 1.1 로그인
//@no-log
POST {{host_url}}/api/v1/auth/login
Content-Type: application/json

{
  "serial_id": "{{auth.API_1_1.serial_id}}",
  "password": "{{auth.API_1_1.password}}"
}

### 1.2 로그아웃
//@no-log
POST {{host_url}}/api/v1/auth/logout

### 1.3 어드민 회원가입
//@no-log
POST {{host_url}}/api/v1/auth/sign-up-admin
Content-Type: application/json

{
  "serial_id": "{{auth.API_1_3.serial_id}}",
  "password": "{{auth.API_1_3.password}}",
  "admin_auth_code": ""
}

### 1.4 회원가입 일괄처리
//@no-log
POST {{host_url}}/api/v1/auth/sign-up
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file" ; filename="test.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< /Users/kyeom/Desktop/test.xlsx

--boundary

### 1.5 비밀번호 변경
//@no-log
PATCH {{host_url}}/api/v1/auth/password
Content-Type: application/json

{
  "current_password": "{{auth.API_1_5.current_password}}",
  "new_password": "{{auth.API_1_5.new_password}}"
}
