### 0.1 현재 기간 조회
// @no-log
GET {{host_url}}/api/v1/system-settings/current-period

### 0.2 기간 정보 수정
// @no-log
PUT {{host_url}}/api/v1/admins/system-settings
Content-Type: application/json

{
  "idea_submission_start" : "2025-02-24T00:00:00",
  "idea_submission_end" : "2025-06-02T23:59:59",
  "phase1_team_building_start": "2025-06-03T00:00:00",
  "phase1_team_building_end" : "2025-06-08T23:59:59",
  "phase1_confirmation_start": "2025-06-09T00:00:00",
  "phase1_confirmation_end" : "2025-06-14T23:59:59",
  "phase2_team_building_start": "2025-06-15T00:00:00",
  "phase2_team_building_end" : "2025-06-18T23:59:59",
  "phase2_confirmation_start": "2025-06-19T00:00:00",
  "phase2_confirmation_end" : "2025-06-20T23:59:59",
  "phase3_team_building_start": "2025-06-21T00:00:00",
  "phase3_team_building_end" : "2025-06-24T23:59:59",
  "phase3_confirmation_start": "2025-06-25T00:00:00",
  "phase3_confirmation_end" : "2025-06-30T23:59:59"
}
