### 4.1 (어드민) 팀 추가하기
//@no-log
POST {{host_url}}/api/v1/admins/teams
Content-Type: application/json

{
  "generation": 4,
  "name": "테스트팀",
  "pm_capacity": 0,
  "pd_capacity": 1,
  "fe_capacity": 1,
  "be_capacity": 1
}

### 4.2 (어드민) 특정 팀에 멤버 추가
//@no-log
POST {{host_url}}/api/v1/admins/teams/3/members
Content-Type: application/json

{
  "role" : "BE",
  "user_id": 3
}

### 4.3 어드민 팀 요약 리스트 조회
// @no-log
GET {{host_url}}/api/v1/admins/teams/overviews?page=1&size=10&generation=4&sorting=ASC&sort-type=TEAM_NAME


### 4.4 어드민 팀 상세 정보 조회
// @no-log
GET {{host_url}}/api/v1/admins/teams/2/details

### 4.5 어드민 팀원 정보 요약 리스트 조회
// @no-log
GET {{host_url}}/api/v1/admins/teams/2/members/overviews

### 4.6 팀 정보 조회
// @no-log
GET {{host_url}}/api/v1/users/teams/details?generation=4

### 4.7 어드민 팀 정보 수정
// @no-log
PUT {{host_url}}/api/v1/admins/teams/2
Content-Type: application/json

{
  "number": 0,
  "team_name": "수정된 팀이름",
  "pm_capacity": 1,
  "pd_capacity": 1,
  "fe_capacity": 1,
  "be_capacity": 1,
  "service_name": "수정된 서비스 이름",
  "leader_id": 2
}

### 4.8 어드민 팀원 팀장 임명
// @no-log
PATCH {{host_url}}/api/v1/admins/members/2/is-leader


### 4.9 팀 정보 수정
// @no-log
PATCH {{host_url}}/api/v1/users/teams
Content-Type: application/json

{
    "generation": 4,
    "name": "팀이름"
}