### 3.1 아이디어 생성
//@no-log
POST {{host_url}}/api/v1/users/ideas
Content-Type: application/json

{
  "idea_info":
  {
    "idea_subject_id": {{idea.API_3_1.idea_info.idea_subject_id}},
    "title": "{{idea.API_3_1.idea_info.title}}",
    "summary": "{{idea.API_3_1.idea_info.summary}}",
    "content": "{{idea.API_3_1.idea_info.content}}",
    "generation": {{idea.API_3_1.idea_info.generation}},
    "provider_role": "{{idea.API_3_1.idea_info.provider_role}}"
  },
  "requirements":
  {
    "pm":
    {
      "requirement": "{{idea.API_3_1.requirements.pm.requirement}}",
      "capacity": {{idea.API_3_1.requirements.pm.capacity}},
      "required_tech_stacks": ["bash"]
    },
    "pd":
    {
      "requirement": "{{idea.API_3_1.requirements.pd.requirement}}",
      "capacity": {{idea.API_3_1.requirements.pd.capacity}},
      "required_tech_stacks": ["bash"]
    },
    "fe":
    {
      "requirement": "{{idea.API_3_1.requirements.fe.requirement}}",
      "capacity": {{idea.API_3_1.requirements.fe.capacity}},
      "required_tech_stacks": ["bash"]
    },
    "be":
    {
      "requirement": "{{idea.API_3_1.requirements.be.requirement}}",
      "capacity": {{idea.API_3_1.requirements.be.capacity}},
      "required_tech_stacks": ["bash", "java"]
    }
  }
}

### 3.2 아이디어 주제 생성
//@no-log
POST {{host_url}}/api/v1/admins/idea-subjects
Content-Type: application/json

{
  "name": "{{idea.API_3_2.name}}"
}

### 3.3 아이디어 주제 노출 상태 토글(활성화 or 비활성화)
//@no-log
POST {{host_url}}/api/v1/admins/idea-subjects/2/toggle-active

### 3.4 아이디어 지원
//@no-log
POST {{host_url}}/api/v1/users/ideas/9/applies
Content-Type: application/json

{
    "phase": 1,
    "preference": 1,
    "motivation" : "열심히하겠습니다.",
    "role": "BE"
}

### 3.5 북마크 토글(생성 or 삭제)
//@no-log
POST {{host_url}}/api/v1/users/ideas/9/bookmarks

### 3.6 아이디어 요약 리스트 조회
//@no-log
GET {{host_url}}/api/v1/users/ideas/overviews?page=1&size=10&generation=4&subject-id=1

### 3.7 내 아이디어 상세 조회
//@no-log
GET {{host_url}}/api/v1/users/ideas/details

### 3.8 아이디어 상세 조회
//@no-log
GET {{host_url}}/api/v1/users/ideas/9/details

### 3.9 아이디어 주제 간단 리스트 조회
//@no-log
GET {{host_url}}/api/v1/idea-subjects/briefs