name: Web Application Develop Server CI/CD

on:
  pull_request:
    branches: [ "dev" ]
    types:
      - opened
      - synchronize
      - closed

jobs:
  CI:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Node.js 환경 설정 및 캐시 활용
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # .env 파일 추가
      - name: Add .env
        run: |
          echo "${{ secrets.ENV }}" | base64 --decode > ./.env

      # 의존성 설치
      - name: Install Dependencies
        run: |
          npm install

      # 프로젝트 빌드
      - name: Build NestJS Application
        run: |
          npm run build

      # Docker Image Build and Push (PR이 merge된 경우 실행)
      - name: Login to Docker Hub
        if: github.event.pull_request.merged == true
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        if: github.event.pull_request.merged == true
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        if: github.event.pull_request.merged == true
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}

  # Pull Request가 Closed되면서 Merge된 경우 배포 진행
  CD:
    if: github.event.pull_request.merged == true
    needs: [CI]

    runs-on: ubuntu-20.04

    steps:
      # SSH를 활용한 배포
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USERNAME }}
          key: ${{ secrets.DEV_SSH_KEY }}
          port: ${{ secrets.DEV_SSH_PORT }}
          script: |
            docker stop api-server || true
            docker rm api-server || true
            docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }} || true
            docker run -d -p 3000:3000 --name api-server --network ${{ secrets.DOCKER_NETWORKNAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}
            
            # 사용되지 않는 이미지 정리
            docker image prune -f